### PR TITLE
OE-Models

### PR DESCRIPTION
**Pull request by ousamasama**
## Link to Ticket
[Project Board](https://github.com/talkative-tangs/Bangazon-API/projects/1)

## Description of Proposed Changes
-Initial database model creation.
-Re-implemented safedelete after not using it during sprint 2.
-Added Customer View/Serializer/URL.
-Adjusted requirements.txt
-Need to fix Issue #1 Search. Added to todo list.

## Steps to Test

After migrating your databases, check to ensure correctness and validity.

```sh
git fetch --all
git checkout oe-models

```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Models
* Views
* Serializers
* URLs

## Mentions @username

@robbyhecht  
@BryanNilsen
@laboyd001

### CODE REVIEW

**Comment by laboyd001** [comment]
👍 
models look good

**Comment by BryanNilsen** [comment]
👍 👍

**Review by robbyhecht — APPROVED** [review]
👍👍👍

**Comment by laboyd001** [comment]
🦆 
I see all the models in db browser and I'm able to see the customer view in the api browser

**Comment by BryanNilsen** [comment]
I pulled down the branch, ran the pip install requirements and made the migrations.
Database looks as expected in DB Browser.

**Pull request merged**
